### ISSUE TITLE
decide on a markup

### ISSUE THREAD

**Issue by willkg** [Osmose/away-team-cookbook#2]
Need to decide on a text markup to use as well as a framework for generating a website, PDF and ebook formats. We can use the ebook/PDF formats on our FirefoxOS devices in the kitchen. We can use the PDF to make a physical book to give to people. We can use the website to sell sickening amounts of advertising and make us all a million dollars so we can buy an island and retire.

**Comment by willkg** [comment]
I've written books using Sphinx and reStructuredText before, so I know that process works.

I recently read about MkDocs which is Markdown based and generates a website. We could extend that using asm.js and web components to generate LaTeX and ebooks and all that other stuff.

We could write our own system.

Are there other options?

**Comment by Osmose** [comment]
Sphinx + RST is best IMO, no need to reinvent the wheel here.
